import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { EntityType } from 'generated/prisma';
import { StoreResponseDto } from 'src/store/dto/store-response.dto';
import { ProductResponseDto } from 'src/product/dto/product-response.dto';
import { PromotionResponseDto } from 'src/promotion/dto/promotion-response.dto';

/**
 * View Response DTO
 * 
 * Response DTO for view records returned from the Views API.
 * Contains the view metadata and optionally includes populated entity data.
 * 
 * **Structure:**
 * - Core view metadata (id, userId, entityType, entityId, viewedAt)
 * - Optional populated entity data (store, product, or promotion)
 * 
 * **Entity Population:**
 * When listing views, the related entity can be included using Prisma's include option.
 * Only the field matching the entityType will be populated:
 * - If entityType is STORE, the `store` field will be populated
 * - If entityType is PRODUCT, the `product` field will be populated
 * - If entityType is PROMOTION, the `promotion` field will be populated
 * 
 * **Use Cases:**
 * - Display user's viewing history with entity details
 * - Build "recently viewed" sections in the UI
 * - Track user engagement patterns
 * - Generate personalized recommendations
 * 
 * @example
 * ```json
 * {
 *   "id": 1,
 *   "userId": 5,
 *   "entityType": "PRODUCT",
 *   "entityId": 42,
 *   "viewedAt": "2024-01-15T10:30:00.000Z",
 *   "product": {
 *     "id": 42,
 *     "name": "iPhone 15 Pro",
 *     "price": "999.99",
 *     "imageUrl": "https://example.com/image.jpg"
 *   }
 * }
 * ```
 */
export class ViewResponseDto {
  /**
   * Unique identifier for this view record
   * 
   * Auto-generated by the database on record creation.
   * 
   * @example 1
   */
  @ApiProperty({ 
    example: 1, 
    description: 'Unique identifier for this view record',
    type: Number,
  })
  id: number;

  /**
   * ID of the user who viewed the entity
   * 
   * References the authenticated user who recorded this view.
   * All views are associated with a specific user.
   * 
   * @example 5
   */
  @ApiProperty({ 
    example: 5, 
    description: 'ID of the user who viewed the entity. References the User table.',
    type: Number,
  })
  userId: number;

  /**
   * Type of entity that was viewed
   * 
   * Categorizes the view by entity type. Used to determine which
   * entity details to populate and how to filter views.
   * 
   * @example EntityType.PRODUCT
   */
  @ApiProperty({
    enum: EntityType,
    example: EntityType.PRODUCT,
    description: 'Type of entity that was viewed. Determines which entity data is populated in the response.',
    enumName: 'EntityType',
  })
  entityType: EntityType;

  /**
   * ID of the entity that was viewed
   * 
   * References the specific store, product, or promotion that was viewed.
   * Combined with userId and entityType, forms a unique constraint.
   * 
   * @example 42
   */
  @ApiProperty({ 
    example: 42, 
    description: 'ID of the entity that was viewed (store ID, product ID, or promotion ID depending on entityType)',
    type: Number,
  })
  entityId: number;

  /**
   * Timestamp when the entity was last viewed by this user
   * 
   * **Behavior:**
   * - Set to current timestamp when first viewing an entity
   * - Updated to current timestamp on subsequent views of the same entity
   * - Automatically managed by Prisma's @updatedAt directive
   * 
   * **Use Cases:**
   * - Sort views by recency
   * - Filter views by date range
   * - Track how recently a user engaged with an entity
   * 
   * @example "2024-01-15T10:30:00.000Z"
   */
  @ApiProperty({
    example: '2024-01-15T10:30:00.000Z',
    description: 'ISO 8601 timestamp of when the entity was last viewed. Automatically updated on subsequent views of the same entity.',
    type: String,
    format: 'date-time',
  })
  viewedAt: Date;

  /**
   * Optional populated store data
   * 
   * **Populated when:**
   * - entityType is STORE
   * - Prisma include option is used in the query
   * - The referenced store still exists
   * 
   * **Contains:**
   * Full store details including name, description, location, images, etc.
   * 
   * **Use Case:**
   * Display store details in "recently viewed stores" section
   * without making additional API calls.
   */
  @ApiPropertyOptional({
    type: () => StoreResponseDto,
    description: 'Full store details. Only populated when entityType is STORE and the view query includes store data.',
  })
  store?: StoreResponseDto;

  /**
   * Optional populated product data
   * 
   * **Populated when:**
   * - entityType is PRODUCT
   * - Prisma include option is used in the query
   * - The referenced product still exists
   * 
   * **Contains:**
   * Full product details including name, price, stock, images, etc.
   * 
   * **Use Case:**
   * Display product cards in "recently viewed products" carousel
   * without making additional API calls.
   */
  @ApiPropertyOptional({
    type: () => ProductResponseDto,
    description: 'Full product details. Only populated when entityType is PRODUCT and the view query includes product data.',
  })
  product?: ProductResponseDto;

  /**
   * Optional populated promotion data
   * 
   * **Populated when:**
   * - entityType is PROMOTION
   * - Prisma include option is used in the query
   * - The referenced promotion still exists
   * 
   * **Contains:**
   * Full promotion details including title, deal type, discount values, etc.
   * 
   * **Use Case:**
   * Display promotion cards in "promotions you've viewed" section
   * without making additional API calls.
   */
  @ApiPropertyOptional({
    type: () => PromotionResponseDto,
    description: 'Full promotion details. Only populated when entityType is PROMOTION and the view query includes promotion data.',
  })
  promotion?: PromotionResponseDto;
}

/**
 * View Count Response DTO
 * 
 * Response DTO for entity view count queries via the public count endpoint.
 * Returns the total number of unique users who have viewed a specific entity.
 * 
 * **Key Insight:**
 * Since the View table enforces uniqueness per user-entity pair,
 * the view count represents the number of unique users who have
 * viewed the entity at least once.
 * 
 * **Use Cases:**
 * - Display view counts on product/store/promotion pages
 * - Sort entities by popularity (most viewed)
 * - Generate trending items lists
 * - Track engagement metrics over time
 * - A/B testing effectiveness measurement
 * 
 * **Note:** This is a public endpoint and doesn't require authentication,
 * making it suitable for display on public-facing pages.
 * 
 * @example
 * ```json
 * {
 *   "entityType": "PRODUCT",
 *   "entityId": 42,
 *   "viewCount": 1547
 * }
 * ```
 */
export class ViewCountResponseDto {
  /**
   * Type of entity being queried
   * 
   * Echoes back the entityType from the request for confirmation.
   * 
   * @example EntityType.PRODUCT
   */
  @ApiProperty({
    enum: EntityType,
    example: EntityType.PRODUCT,
    description: 'Type of entity (STORE, PRODUCT, or PROMOTION) for which the view count was requested',
    enumName: 'EntityType',
  })
  entityType: EntityType;

  /**
   * ID of the entity being queried
   * 
   * Echoes back the entityId from the request for confirmation.
   * 
   * @example 42
   */
  @ApiProperty({ 
    example: 42, 
    description: 'ID of the entity for which the view count was requested',
    type: Number,
  })
  entityId: number;

  /**
   * Total number of unique user views
   * 
   * Represents the count of distinct users who have viewed this entity
   * at least once. Multiple views by the same user count as only one.
   * 
   * **Interpretation:**
   * - 0: No users have viewed this entity
   * - 1-99: Low visibility entity
   * - 100-999: Moderate engagement
   * - 1000+: High engagement/popular entity
   * 
   * @example 1547
   */
  @ApiProperty({ 
    example: 1547, 
    description: 'Total number of unique users who have viewed this entity. Each user is counted only once regardless of how many times they viewed it.',
    type: Number,
    minimum: 0,
  })
  viewCount: number;
}
